name             'cloudera'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures cloudera'
long_description 'Installs/Configures cloudera'
version          '0.1.0'

depends "selinux", '~> 0.8.0'
depends "hostsfile", '~> 2.4.5'